-- * add extra plugins
-- * disable/enabled LazyVim plugins
-- * override the configuration of LazyVim plugins
-- disable trouble
--
-- IT DOES NOT WORK
-- return {
--   { "semshi", enabled = false },
--   { "neocmake", enabled = false },
--   { "venv-select", enabled = false },
-- }
